name: baby_hub
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

# All packages used
dependencies:
  flutter:
    sdk: flutter

  # utility packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.1.0
  url_launcher: ^6.2.5
  get_storage: ^2.1.1
  flutter_native_splash: ^2.3.13
  smooth_page_indicator: ^1.1.0

  # icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  # state management
  get: ^4.6.6

  # product specific
  google_fonts: ^6.2.1

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # local assets
  assets:
    - assets/logo/
    - assets/images/on_boarding_images/
    - assets/icons/
