// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwH759AcQYnumwJQeI9fX1PtQwC3DyJPg',
    appId: '1:1037508465814:web:8eab37d45938e735f59eb7',
    messagingSenderId: '1037508465814',
    projectId: 'paalii',
    authDomain: 'paalii.firebaseapp.com',
    storageBucket: 'paalii.appspot.com',
    measurementId: 'G-FJ1ZJRYB61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1JeE7J1iPF3uoO6uHmx5HdCAGapsg_As',
    appId: '1:1037508465814:android:f332eeae6c5f966df59eb7',
    messagingSenderId: '1037508465814',
    projectId: 'paalii',
    storageBucket: 'paalii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcZ_mTLCbP4-x6Z2eR_NhVXdxj-EVSc44',
    appId: '1:1037508465814:ios:0de866d6a1e1ae9ef59eb7',
    messagingSenderId: '1037508465814',
    projectId: 'paalii',
    storageBucket: 'paalii.appspot.com',
    iosBundleId: 'com.example.babyHub',
  );
}
